# GitHub Action for generating a contribution snake animation

name: Generate Snake Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    # ⭐️ ADD THIS permissions BLOCK ⭐️
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          # Your GitHub username is retrieved automatically
          github_user_name: ${{ github.repository_owner }}
          
          # The output path for the animation file
          outputs: output/snake.svg
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg
          git commit -m "Generate snake animation"
          git push
